### ISSUE TITLE
Filepaths with ÅÄÖ shown as new/modified

### ISSUE THREAD

**Issue by DeletedScreen** [atom/git-utils#47] opened 2015-07-13 14:02 UTC
Hi!

Even if my git status says that there are no new or modified files, files with unicode characters such as Å, Ä and Ö show up as new or modified.

Example:
![Example2](http://4st.me/VzUw5.png)

Sometimes they don't show up, either, but the folder above them are marked as modified anyway.

Example:
![Example2](http://4st.me/dk0cX.png)

I was referenced by @subesokun - here: https://github.com/subesokun/atom-tree-view-git-status/issues/5#issuecomment-120937158

**Comment by gisenberg** [comment] 2015-09-13 00:13
I tried to reproduce this behavior by creating a new repository containing two committed files (`Atom.txt` and `Ätom.txt`) and running the following test against that repository:

```
    describe 'when a path contains unicode', ->
      it 'returns the status of the given path', ->
        repoDirectory = temp.mkdirSync('node-git-repo-')
        wrench.copyDirSyncRecursive(path.join(__dirname, 'fixtures/unicode.git'), path.join(repoDirectory, '.git'))
        repo = git.open(repoDirectory)

        expect(repo.isStatusNew('Ätom.txt')).toBe false
        expect(repo.isStatusModified('Ätom.txt')).toBe false
        expect(repo.isStatusNew('Atom.txt')).toBe false
        expect(repo.isStatusModified('Atom.txt')).toBe false 
```

The test passed, as well as other variations using repo.getStatus(), which leads me to believe that the behavior you're seeing is external to git-utils.

**Comment by 50Wliu** [comment] 2015-09-13 01:46
In that case, closing as a duplicate of atom/atom#1890.

**Closed by 50Wliu** 2015-09-13 01:46 UTC
Labels: bug
