### ISSUE TITLE
Basic shortcuts do not work at all on OSX

### ISSUE THREAD

**Issue by scarolan** [atom/git-utils#44] opened 2015-05-26 02:53 UTC
I'm trying to use Atom for a week or two instead of my normal go-to text editor.  The Git integration looked very interesting, so I tried the steps in this blog post:  http://blog.atom.io/2014/03/13/git-integration.html

CMD-ALT-Z works fine for resetting a file to HEAD.

CMD-SHIFT-B doesn't work at all.  I tried editing some files in my git repo, nothing happens when I do this key command.

The color highlighting tips for tree-view also don't work, even though I added the required snippet to my config file.

**Comment by lee-dohm** [comment] 2015-05-26 03:02
I can't replicate the issues you're describing using Atom v0.202.0-3bbbadd on Mac OS X 10.10.3.

Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?
* When you open Atom are you opening the root of a Git repository tree?

**Comment by mindrones** [comment] 2015-08-11 10:17
For me, `shift-cmd-b` doesn't work but the tree-view items are coloured based on git status.

After enabling Keybinding Resolver I've noticed that `shift-cmd-b` wasn't catched at all.

This is when a keybinding resolves to a command:

![atom_keybindings_resolver_resolve](https://cloud.githubusercontent.com/assets/1309648/9195323/47c44a92-4022-11e5-801f-6e4679ff6da7.png)

This is when a keybinding doesn't resolve to a command:

![atom_keybindings_resolver_nomatch](https://cloud.githubusercontent.com/assets/1309648/9195335/5e9a7a16-4022-11e5-8bb7-dbcfb14b7ad3.png)

In the case of `shift-cmd-b` Keybinding Resolver doesn't even catch that I' pressing `shift-cmd-b`:

![atom_keybindings_resolver_nocatch](https://cloud.githubusercontent.com/assets/1309648/9195378/b11aa4f0-4022-11e5-9a31-812a9bd1a025.png)

Could it be that there's some OS-wide shortcut conflict?

> Which version of Atom are you using?

Atom 1.0.5

> What OS and version are you running?

Mac OS X 10.10.4

> Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

yes

> When you open Atom are you opening the root of a Git repository tree?

yes

**Comment by izuzak** [comment] 2015-09-09 19:24
@scarolan @mindrones Which keyboards do you use? US or something else? If you're not using a US keyboard, can you switch to the US keyboard in OSX settings and see if the behavior is different?

**Comment by mindrones** [comment] 2015-09-10 13:16
@izuzak confirming this issue with the US keyboard, but I have filed a [question on Ask Different](http://apple.stackexchange.com/questions/199975/unable-to-type-the-shortcut-command-shift-b-on-yosemite) because I think this is a system issue. While checking for this issue I've discovered I'm not able to press that combination at all, independently from the focused software (forgot to report here sorry).

**Comment by izuzak** [comment] 2015-09-17 09:16
Thanks for letting us know, @mindrones :bow:. Since it seems you're having a wider problem and @scarolan didn't reply with the information asked in https://github.com/atom/git-utils/issues/44#issuecomment-105372341 and https://github.com/atom/git-utils/issues/44#issuecomment-139020776 -- I'm going to close this for now. Happy to reopen if we get more details.

**Closed by izuzak** 2015-09-17 09:16 UTC
Labels: more-information-needed
